import sys
sys.path.append('./../src/')

from gustav import ncbi

import pandas as pd
import re
from tqdm.auto import tqdm
tqdm.pandas()
import numpy as np


pubmed = ncbi.pubmed('main',
                    columns = ['pubmed_id', 'pubdate', 'abstract'],
                    filters = {"pubdate": np.arange(1990, 2021)})


pubmed['abstract'] = pubmed['abstract'].progress_apply(lambda x: x.lower())
# pubmed['title'] = pubmed['title'].progress_apply(lambda x: x.lower())

term_expanded = {5755: ['acanthamoeba castellanii', 'acanthamoeba castellani'],
 7029: ['acyrthosiphon pisum', 'acyrthosiphum pisum', 'pea aphid'],
 5341: ['agaricus bisporus',
  'agaricus bisporus var. albidus (nom. inval.)',
  'agaricus bisporus var. albidus',
  'agaricus brunnescens',
  'button mushroom',
  'common mushroom',
  'cultivated mushroom'],
 28583: ['allomyces macrogynus'],
 529818: ['amastigomonas trahens', 'thecamonas trahens'],
 4881: ['amoebidium parasiticum'],
 29170: ['ancylostoma caninum', 'dog hookworm'],
 28377: ['anolis carolinensis', 'carolina anole', 'green anole'],
 7165: ['african malaria mosquito',
  'anopheles gambiae',
  'anopheles gambiae sensu stricto',
  'anopheles gambiae s'],
 7460: ['apis mellifera',
  'apis mellifica',
  'bee',
  'european honey bee',
  'honeybee',
  'honey bee',
  'western honey bee'],
 6500: ['aplysia californica', 'california sea hare'],
 162425: ['aspergillus nidulans',
  'aspergillus nidulellus',
  'emericella nidulans'],
 8153: ['astatotilapia burtoni',
  "burton's mouthbrooder",
  'chromis burtoni',
  'haplochromis burtoni'],
 109871: ['batrachochytrium dendrobatidis'],
 6526: ['australorbis glabratus',
  'biomphalaria glabrata',
  'bloodfluke planorb',
  'planorbis glabratus'],
 9913: ['bos bovis',
  'bos primigenius taurus',
  'bos taurus',
  'bovine',
  'cattle',
  'cow',
  'dairy cow',
  'domestic cattle',
  'domestic cow'],
 135651: ['caenorhabditis brenneri', 'caenorhabditis cb5161'],
 281687: ['caenorhabditis japonica'],
 31234: ['caenorhabditis remanei', 'caenorhabditis vulgaris'],
 1561998: ['caenorhabditis tropicalis'],
 1094335: ['caenorhabditis afra'],
 1611254: ['caenorhabditis nigoni'],
 9483: ['callithrix jacchus jacchus',
  'callithrix jacchus',
  'common marmoset',
  'white ear-tufted marmoset',
  'white-tufted-ear marmoset'],
 7868: ['australian ghost shark',
  'callorhinchus milii',
  'elephant fish',
  'elephant shark',
  'ghost shark',
  'makorepe',
  'plownose chimaera',
  'reperepe'],
 36911: ['candida lusitaniae',
  'clavispora imtechensis (nom, inval.)',
  'clavispora imtechensis',
  'clavispora lusitaniae'],
 5482: ['atelosaccharomyces tropicalis',
  'candida albicans var. tropicalis',
  'candida tropicalis',
  'castellania tropicalis',
  'endomyces tropicalis',
  'monilia tropicalis',
  'myceloblastanon tropicale',
  'mycotorula tropicalis',
  'oidium tropicale',
  'procandida tropicalis'],
 9615: ['canis canis',
  'canis domesticus',
  'canis familiaris',
  'canis lupus familiaris',
  'dog',
  'dogs'],
 192875: ['capsaspora owczarzaki'],
 10141: ['cavia aperea porcellus',
  'cavia cobaya',
  'cavia porcellus',
  'domestic guinea pig',
  'guinea pig'],
 38033: ['chaetomium globosum', 'chaetomium rectum'],
 9534: ['african green monkey',
  'african green monkeys',
  'ceropithecus aethiops',
  'chlorocebus aethiops',
  'grivet',
  'savanah monkey'],
 9358: ['choloepus hoffmanni',
  "hoffmann's two-fingered sloth",
  "hoffmann's two-toed sloth"],
 8479: ['chrysemys picta',
  'painted turtle',
  'testudo picta',
  'trachemys picta'],
 51511: ['ciona savignyi',
  'pacific transparent sea squirt',
  'transparent tunicate'],
 27828: ['cooperia oncophora'],
 5346: ['agaricus cinereus',
  'coprinopsis cinerea',
  'coprinus cinereus',
  'coprinus macrorhizus (pers.) rea, 1922',
  'hormographiella aspergillata'],
 5207: ['blastomyces neoformans',
  'cryptococcus neoformans',
  'debaryomyces neoformans',
  'filobasidiella neoformans',
  'lipomyces neoformans',
  'saccharomyces neoformans',
  'torula neoformans',
  'torulopsis neoformans'],
 9361: ['dasypus novemcinctus', 'nine-banded armadillo'],
 30656: ['dermoptera', 'flying lemurs'],
 29172: ['bovine lungworm', 'dictyocaulus viviparus'],
 10020: ['dipodomys ordii', "ord's kangaroo rat"],
 7217: ['drosophila ananassae', 'drosophila annanassae'],
 125945: ['drosophila biarmipes'],
 42026: ['drosophila bipectinata'],
 30023: ['drosophila elegans'],
 7220: ['drosophila erecta'],
 29029: ['drosophila eugracilis'],
 30025: ['drosophila ficusphila'],
 7222: ['drosophila grimshawi', 'idiomyia grimshawi'],
 30033: ['drosophila kikkawai'],
 7230: ['drosophila mohavensis', 'drosophila mojavensis'],
 7234: ['drosophila persimilis'],
 1041015: ['drosophila rhopaloa'],
 7238: ['drosophila sechellia'],
 7240: ['drosophila simulans'],
 29030: ['drosophila takahashii'],
 7244: ['drosophila virilis'],
 7260: ['drosophila willistoni'],
 7245: ['drosophila yakuba'],
 9371: ['echinops telfairii',
  'echinops telfairi',
  'lesser hedgehog tenrec',
  'small madagascar hedgehog'],
 28737: ['cape elephant shrew',
  'cape long-eared elephant shrew',
  'elephantulus edwardii'],
 7764: ['bdellostoma burgeri', 'eptatretus burgeri', 'inshore hagfish'],
 9796: ['domestic horse',
  'equine',
  'equus caballus',
  'equus przewalskii f. caballus',
  'equus przewalskii forma caballus',
  'horse'],
 9365: ['common hedgehog',
  'erinaceus europaeus',
  'european hedgehog',
  'western european hedgehog'],
 9685: [
  'cats',
  'domestic cat',
  'felis catus',
  'felis domesticus',
  'felis silvestris catus'],
 9031: ['bantam',
  'chicken',
  'chickens',
  'gallus domesticus',
  'gallus gallus domesticus',
  'gallus gallus'],
 69293: ['gasterosteus aculeatus',
  'three spined stickleback',
  'three-spined stickleback'],
 655981: ['geomyces destructans', 'pseudogymnoascus destructans'],
 37862: ['heterorhabditis bacteriophora'],
 5037: ['ajellomyces capsulatus',
  'cryptococcus capsulatus',
  'emmonsiella capsulata',
  'histoplasma capsulatum'],
 6087: ['hydra attenuata',
  'hydra carnea',
  'hydra littoralis',
  'hydra magnipapillata',
  'hydra vulgaris',
  'swiftwater hydra'],
 232323: ['hypsibius dujardini'],
 429038: ['jassa slatteryi'],
 7897: ['coelacanth', 'latimeria chalumnae'],
 7918: ['lepisosteus oculatus', 'spotted gar'],
 6850: ['atlantic horseshoe crab', 'limulus polyphemus'],
 9844: ['camelus glama', 'lama glama', 'lama guanicoe glama', 'llama'],
 36914: ['lodderomyces elongisporus', 'saccharomyces elongisporus'],
 9785: ['african bush elephant',
  'african savanna elephant',
  'african savannah elephant',
  'loxodonta africana africana',
  'loxodonta africana'],
 7200: ['lutzomyia longipalpis'],
 9541: ['crab eating macaque',
  'crab-eating macaque',
  'cynomolgus macaque',
  'cynomolgus monkey',
  'cynomolgus monkeys',
  'long-tailed macaque',
  'macaca cynomolgus',
  'macaca fascicularis',
  'macaca irus'],
 9544: ['macaca mulatta',
  'rhesus macaque',
  'rhesus macaques',
  'rhesus monkey',
  'rhesus monkeys'],
 143292: ['chinese pangolin', 'manis pentadactyla'],
 106582: ['maylandia zebra',
  'metriaclima zebra',
  "pseudotropheus sp. 'pseudotropheus zebra complex'",
  'pseudotropheus zebra',
  'zebra mbuna'],
 30608: ['gray mouse lemur', 'grey mouse lemur', 'microcebus murinus'],
 63405: ['microsporum canis', 'nannizzia otae'],
 63402: ['achorion gypseum',
  'anamorph of arthroderma gypseum',
  'closterosporia gypsea',
  'gymnoascus gypseus',
  'microsporum gypseum',
  'microsporum gypseum var. vinosum',
  'nannizzia gypsea',
  'sabouraudites gypseus',
  'trichophyton gypseum'],
 79684: ['microtus ochrogaster', 'prairie vole', 'prairie voles'],
 13616: ['gray short-tailed opossum', 'monodelphis domestica'],
 81526: ['monosiga ovata'],
 78898: ['haplosporangium attenuatissimum',
  'haplosporangium fasciculatum',
  'mortierella verticillata',
  'podila verticillata'],
 9669: ['black ferret',
  'domestic ferret',
  'ferret',
  'mustela furo',
  'mustela putorius furo'],
 59463: ['little brown bat', 'myotis lucifugus'],
 7426: ['nasonia giraulti'],
 7427: ['nasonia longicornis'],
 7425: ['jewel wasp', 'nasonia vitripennis'],
 51031: ['necator americanus', 'new world hookworm'],
 28839: ['nematodirus battus'],
 27835: ['nippostrongylus brasiliensis'],
 61853: ['hylobates concolor leucogenys',
  'hylobates concolor leucogyneus',
  'hylobates leucogenys leucogenys',
  'hylobates leucogenys',
  'nomascus leucogenys leucogenys',
  'nomascus leucogenys',
  'nomascus leukogenys',
  'northern white-cheeked gibbon',
  'white-cheeked gibbon'],
 9315: ['macropus eugenii', 'notamacropus eugenii', 'tammar wallaby'],
 154970: ['nuclearia simplex'],
 9978: ['american pika', 'ochotona princeps', 'southern american pika'],
 61180: ['nodule worm', 'oesophagostomum dentatum', 'pig nodule worm'],
 8128: ['nile tilapia',
  'oreochromis nilotica',
  'oreochromis niloticus',
  'perca nilotica',
  'tilapia nilotica'],
 9258: ['duck-billed platypus',
  'duckbill platypus',
  'ornithorhynchus anatinus',
  'platypus anatinus',
  'platypus'],
 9986: ['domestic rabbit',
  'european rabbit',
  'japanese white rabbit',
  'lepus cuniculus',
  'oryctolagus cuniculus',
  'rabbit',
  'rabbits'],
 6317: ['ostertagia ostertagi'],
 30611: ['galago garnettii',
  'galago garnetti',
  'otolemur garnettii',
  'small-eared galago'],
 1172189: ['oxytricha trifallax'],
 9597: ['bonobo', 'pan paniscus', 'pygmy chimpanzee'],
 9598: ['chimpanzee', 'pan troglodytes'],
 9557: ['baboon',
  'hamadryas baboon',
  'papio hamadryas',
  'papio hamadryas subsp.',
  'red baboon',
  'sacred baboon',
  'western baboon'],
 257977: ['haplochromis chilotes',
  'paralabidochromis chilotes',
  'paratilapia chilotes'],
 121225: ['body lice',
  'head lice',
  'human lice',
  'human louse',
  'pediculus humanus'],
 42520: ['california mouse', 'peromyscus californicus'],
 10041: ['peromyscus leucopus', 'white-footed mouse'],
 10042: ['north american deer mouse', 'peromyscus maniculatus'],
 42413: ['oldfield mouse', 'peromyscus polionotus'],
 7757: ['marine lamprey', 'petromyzon marinus', 'sea lamprey', 'sea lampreys'],
 29031: ['phlebotomus papatasii',
  'phlebotomus papatasi',
  'phlebotomus (phlebotomus) papatasi'],
 5791: ['physarum polycephalum'],
 4754: ['pneumocystis carinii f. sp. carinii',
  'pneumocystis carinii f. sp. ratti',
  'pneumocystis carinii'],
 2587412: ['malinvernia anserina',
  'podospora anserina',
  'triangularia anserina'],
 9600: ['bornean orangutan',
  'orang utan',
  'orang-utan',
  'orangutan',
  'pongo pygmaeus'],
 37621: ['priapula caudata', 'priapulus caudatus'],
 54126: ['pristionchus pacificus'],
 9813: ['cape hyrax',
  'cape rock hyrax',
  'large-toothed rock hyrax',
  'procavia capensis',
  'rock dassie',
  'rock hyrax'],
 132908: ['large flying fox', 'pteropus vampyrus'],
 7782: ['leucoraja erinacea',
  'little skate',
  'raja erinacea',
  'raja erinaceus',
  'raja erinacia'],
 64495: ['rhizopus arrhizus',
  'rhizopus arrhizus var. arrhizus',
  'rhizopus arrhizus var. tonkinensis',
  'rhizopus chiuniang',
  'rhizopus formosaensis',
  'rhizopus hangchow',
  'rhizopus javanicus',
  'rhizopus liquefaciens',
  'rhizopus peka',
  'rhizopus pseudochinensis',
  'rhizopus suinus',
  'rhizopus tamari',
  'rhizopus thermosus',
  'rhizopus tonkinensis',
  'rhizopus tritici'],
 13249: ['rhodnius prolixus'],
 4932: ["baker's yeast",
  "brewer's yeast",
  'candida robusta',
  'mycoderma cerevisiae',
  'saccharomyces capensis',
  'saccharomyces cerevisiae',
  'saccharomyces italicus',
  'saccharomyces oviformis',
  'saccharomyces uvarum var. melibiosus',
  's. cerevisiae'],
 27679: ['bolivian squirrel monkey', 'saimiri boliviensis'],
 946362: ['proterospongia sp. atcc 50818',
  'salpingoeca rosetta atcc 50818',
  'salpingoeca rosetta atcc50818',
  'salpingoeca rosetta'],
 4897: ['hasegawaea japonica',
  'schizosaccharomyces japonicus',
  'schizosaccharomyces japonicus var. japonicus',
  'schizosaccharomyces japonicus var. versatilis'],
 4899: ['schizosaccharomyces octosporus'],
 79327: ['dugesia mediterranea',
  'dugesia (schmidtea) mediterranea',
  'freshwater planarian',
  'schmidtea mediterranea'],
 42254: ['eurasian shrew', 'european shrew', 'sorex araneus'],
 72019: ['sphaeroforma arctica',
  'sphaerosoma arcticum',
  'sphaerosoma arcticus'],
 109760: ['phlyctochytrium punctatum', 'spizellomyces punctatus'],
 126957: ['strigamia maritima'],
 7668: ['purple sea urchin', 'purple urchin', 'strongylocentrotus purpuratus'],
 59729: ['poephila guttata',
  'taeniopygia guttata',
  'taenopygia guttata',
  'zebra finch'],
 1868482: ['carlito syrichta', 'philippine tarsier', 'tarsius syrichta'],
 45464: ['ostertagia circumcincta', 'teladorsagia circumcincta'],
 5911: ['tetrahymena thermophila'],
 7070: ['red flour beetle', 'rust-red flour beetle', 'tribolium castaneum'],
 6334: ['trichinella spiralis'],
 63418: ['trichophyton equinum'],
 5551: ['epidermophyton rubrum',
  'microsporum rubrum',
  'sabouraudites ruber (cazalbou) nann., 1934',
  'sabouraudites ruber',
  'trichophyton fischeri',
  'trichophyton kanei',
  'trichophyton megninii',
  'trichophyton raubitschekii',
  'trichophyton rubrum',
  'trichophyton rubrum var. raubitschekii'],
 34387: ['oidium tonsurans',
  'trichomyces tonsurans',
  'trichophyton tonsurans'],
 10228: ['trichoplax adhaerens'],
 40352: ['trichostrongylus vitrinus'],
 37347: ['common tree shrew',
  'northern tree shrew',
  'tupaia belangeri',
  'tupaia glis belangeri'],
 9739: ['atlantic bottlenose dolphin',
  'bottle-nosed dolphin',
  'common bottlenose dolphin',
  'tursiops truncatus'],
 33188: ['gymnoascus siglerae', 'uncinocarpus reesii'],
 5270: ['ustilago maydis'],
 30538: ['alpaca', 'lama guanicoe pacos', 'lama pacos', 'vicugna pacos'],
 2950: ['symbiodinium sp.'],
 4779: ['bremia lactucae', 'lettuce downy mildew'],
 4781: ['peronospora halstedii', 'plasmopara halstedii'],
 4803: ['lagenidium giganteum'],
 4837: ['phycomyces blakesleeanus'],
 4841: ['mucor racemosus', 'rhizomucor racemosus'],
 4909: ['candida acidothermophilum',
  "'candida glycerinogenes'",
  'issatchenkia orientalis',
  'pichia kudriavzevii',
  'saccharomyces krusei'],
 5039: ['ajellomyces dermatitidis',
  'blastomyces dermatitidis',
  'blastomycoides dermatitidis'],
 5057: ['aspergillus clavatus'],
 5059: ['aspergillus flavus',
  'aspergillus flavus var. parvisclerotigenus',
  'aspergillus parvisclerotigenus',
  'petromyces flavus'],
 5061: ['aspergillus lacticoffeatus', 'aspergillus niger'],
 5076: ['penicillium chrysogenum',
  'penicillium chrysogeum',
  'penicillium notatum'],
 5180: ['sclerotinia sclerotiorum'],
 5272: ['microbotryum violaceum',
  'uredo violacea pers., 1797',
  'ustilago violacea'],
 5334: ['schizophyllum commune'],
 5507: ['fusarium oxysporum'],
 5518: ['fusarium graminearum',
  'gibberella zeae (schwein.) petch, 1936',
  'sphaeria zeae'],
 5970: ['exophiala dermatitidis',
  'hormiscium dermatitidis',
  'wangiella dermatitidis'],
 6941: ['boophilus microplus',
  'cattle tick',
  'rhipicephalus (boophilus) microplus',
  'rhipicephalus microplus',
  'southern cattle tick'],
 7370: ['house fly', 'musca domestica'],
 7579: ['terebratulina'],
 7739: ['amphioxus floridae', 'branchiostoma floridae', 'florida lancelet'],
 7797: ['spiny dogfish', 'squalus acanthias'],
 8022: ['oncorhynchus mykiss',
  'oncorhynchus nerka mykiss',
  'parasalmo mykiss',
  'rainbow trout',
  'salmo mykiss'],
 8509: ['squamata', 'squamates'],
 9103: ['common turkey', 'meleagris gallopavo', 'turkey', 'wild turkey'],
 9509: ['ateles geoffroyi',
  'black-handed spider monkey',
  'central american spider monkey'],
 9516: ['cebus capucinus',
  'white-faced capuchin',
  'white-faced sapajou',
  'white-throated capuchin'],
 9823: ['pig', 'pigs', 'sus scrofa', 'swine', 'wild boar'],
 10181: ['heterocephalus glaber', 'naked mole rat', 'naked mole-rat'],
 10195: ['brachionus plicatilis'],
 10224: ['saccoglossus kowalevskii', 'saccoglossus kowalevskyi'],
 13686: ['imported red fire ant',
  'red fire ant',
  'red imported fire ant',
  'solenopsis invicta'],
 27350: ['puccinia striiformis'],
 27602: ['balaena mysticetus',
  'bowhead',
  'bowhead whale',
  'greenland right whale'],
 28574: ['penicillium minioluteum',
  'penicillium miniolutum',
  'penicillium samsonii',
  'talaromyces minioluteus'],
 29879: ['neurospora discreta'],
 29908: ['rhinocladium schenckii',
  'sporothrix schenckii',
  'sporotrichum schenckii'],
 30301: ['botryllus schlosseri'],
 30637: ["ehrenberg's mole-rat",
  'nannospalax ehrenbergi',
  'palestine mole rat',
  'spalax ehrenbergii',
  'spalax ehrenbergi'],
 33178: ['aspergillus terrestris', 'aspergillus terreus'],
 33431: ['crimson-patched longwing', 'heliconius erato'],
 33495: ['discinisca'],
 33498: ['discina striata'],
 34373: ['blumeria graminis', 'erysiphe graminis', 'grass mildew'],
 34508: ['neoaplectana carpocapsae', 'steinernema carpocapsae'],
 34740: ['common postman', 'heliconius melpomene', 'postman butterfly'],
 36630: ['aspergillus fischerianus',
  'aspergillus fischeri',
  'neosartorya fischeri'],
 37727: ['penicillium marneffei', 'talaromyces marneffei'],
 38358: ['bradysia coprophila', 'sciara coprophila'],
 40127: ['neurospora tetrasperma'],
 41045: ['pythium oligandrum'],
 42251: ['tuber borchii', 'whitish truffle'],
 45286: ['eremothecium sinecaudum',
  'holleya sinecauda',
  'nematospora sinecauda'],
 50663: ['caenocholax fenyesi'],
 64657: ['tremella fuciformis'],
 65070: ['pythium aphanidermatum', 'rheosporangium aphanidermatum'],
 65357: ['aecidium candidum', 'albugo candida'],
 70743: ['peronospora sparsa'],
 71150: ['agaricus involutus', 'paxillus involutus'],
 74722: ['oidium chartarum',
  'oospora chartarum',
  'stachybotrys chartarum',
  'stilbospora chartarum'],
 96448: ['philodina roseola'],
 104759: ['porites lobata'],
 104777: ['brachionus calyciflorus'],
 104782: ['adineta vaga'],
 104786: ['habrotrocha constricta'],
 106881: ['king of the sea', 'latimeria menadoensis', 'menado coelacanth'],
 107463: ['xanthoria parietina'],
 110368: ['bicyclus anynana', 'squinting bush brown'],
 114742: ['pythium insidiosum'],
 117187: ['fusarium moniliforme',
  'fusarium verticillioides',
  'gibberella moniliformis',
  'oospora verticillioides'],
 121759: ['loboa loboi', 'paracoccidioides brasiliensis'],
 123356: ['hyaloperonospora parasitica', 'peronospora parasitica'],
 143960: ['coelomomyces stegomyiae'],
 148305: ['pyricularia grisea'],
 169388: ['fusarium solani', 'fusisporium solani', 'neocosmospora solani'],
 183141: ['brachionus ibericus'],
 199306: ['coccidioides posadasii'],
 204045: ['schizosaccharomyces kambucha'],
 208348: ['puccinia triticina', 'wheat leaf rust'],
 249248: ['adineta ricciae'],
 317944: ['crania', 'neocrania', 'novocrania'],
 492056: ['phoronis pallida'],
 672012: ['phoronis architecta'],
 672013: ['phoronis vancouverensis'],
 1047171: ['mycosphaerella graminicola',
  'septoria tritici',
  'zymoseptoria tritici'],
 1859096: ['cryptococcus gattii vgii'],
 2052682: ['globisporangium ultimum', 'pythium ultimum']}
isolated_patterns = []

for pattern in term_expanded:
	isolated_patterns.append(re.compile("|".join(np.array(["\\b"+ re.escape(i.lower()) + "\\b" for i in term_expanded[pattern]]))))


together = np.zeros((pubmed.shape[0], len(term_expanded)))

for i, pattern in tqdm(enumerate(isolated_patterns), total = len(term_expanded)):
	together[:, i] =  np.array(pubmed['abstract'].progress_apply(lambda x: False if pattern.search(x) is None else True))


np.save('../../manuscript/cache/abstract_matched_nhgri_organisms', together)