[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_utils"
# "cdylib" is necessary to produce a shared library for Python to import from.
path = "lib.rs"

crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.15.0"
features = ["extension-module"]